### ISSUE TITLE
Failed: PersistenceIdsQuerySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-spanner#86]
https://travis-ci.com/github/akka/akka-persistence-spanner/jobs/329804266

```
[info] PersistenceIdsQuerySpec:
560[info] akka.persistence.spanner.PersistenceIdsQuerySpec *** ABORTED *** (3 seconds, 143 milliseconds)
561[info]   java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Done
562[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
563[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:165)
564[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:143)
565[info]   at akka.persistence.spanner.PersistenceIdsQuerySpec.beforeAll(PersistenceIdsQuerySpec.scala:25)
566[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
567[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
568[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
569[info]   at akka.persistence.spanner.SpannerSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(SpannerSpec.scala:317)
```

**Comment by chbatey** [comment]
Travis logs are done as it has been re-run. We should copy more of the logs into the ticket for travis CI.
